CREATE EXTERNAL TABLE DANECW
(
    dData CHARACTER VARYING(200),
    ENERGY REAL,
    DAYLENGTH REAL,
    SEASON REAL,
	CATEGORY CHARACTER VARYING(200)
)
USING
(
    DATAOBJECT('/export/home/nz/predykcja/daneCWdate.csv')
    DELIMITER ';'
    LOGDIR '/tmp'
);

