CREATE EXTERNAL TABLE DANECO
(
    dData CHARACTER VARYING(200),
    ID INTEGER,
    ENERGY REAL,
    TEMP REAL,
    WIND INTEGER,
    HUMID INTEGER,
    CLOUD INTEGER,
    DAYLENGTH REAL,
    DAYTIME REAL,
    SEASON REAL,
    ROWCOUNT INTEGER
)
USING
(
    DATAOBJECT('/export/home/nz/predykcja/daneCO.csv')
    DELIMITER ';'
    LOGDIR '/tmp'
);

CREATE EXTERNAL TABLE DANECW
(
    dData CHARACTER VARYING(200),
    ID INTEGER,
    ENERGY REAL,
    TEMP REAL,
    WIND INTEGER,
    HUMID INTEGER,
    CLOUD INTEGER,
    DAYLENGTH REAL,
    DAYTIME REAL,
    SEASON REAL,
    ROWCOUNT INTEGER
)
USING
(
    DATAOBJECT('/export/home/nz/predykcja/daneCW.csv')
    DELIMITER ';'
    LOGDIR '/tmp'
);